// Generated by https://quicktype.io

export interface User {
  id?:                number;
  name?:              string;
  email?:             string;
  email_verified_at?: string;
  password?:          string;
  city?:              string;
  remember_token?:    string;
  created_at?:        string;
  updated_at?:        string;
}
